# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e60484211f4a708e6d595ab676546eea0983788bc86f3714d4e3ba3a1a89f1e80a1c481f1072358403c6c2f7c629d5caf8b840d747ba5d47acca276501d3a28a

test:
  secret_key_base: 93a9aa1d0ec47849b21568d93c5495d4a064ffe902df238fc89623fdbb544c931515fa6d2809416554e2ee0f0431c1bf855ebc22d922cb2dc0b43671e164afac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
